<?php
/**
 * @var string $fieldName
 * @var string $fieldMethod
 * @var string $returnSelf
 */
?>
public function <?php echo $fieldName;?>() :bool {
    return $this->_getBooleanVal('<?php echo $fieldName;?>');
}
/** @return <?php echo $returnSelf;?>
 */
public function set<?php echo $fieldMethod;?>(bool $<?php echo $fieldName;?>)  {
    $this->_setBooleanVal('<?php echo $fieldName;?>', $<?php echo $fieldName;?>);
    return $this;
}