<?php
/**
 * @var string $fieldName
 * @var string $fieldMethod
 * @var string $returnSelf
 */
?>
public function get<?php echo $fieldMethod;?>(): ?\Carbon\Carbon {
    return $this->_getDateTimeVal('<?php echo $fieldName;?>');
}
public function get<?php echo $fieldMethod;?>Formatted(string $format = null) :string {
    return $this->_getDateTimeFormattedVal('<?php echo $fieldName;?>', $format);
}
public function has<?php echo $fieldMethod;?>() :bool {
    return $this->_hasDateTimeVal('<?php echo $fieldName;?>');
}
/** @return <?php echo $returnSelf;?>
*/
public function set<?php echo $fieldMethod;?>($<?php echo $fieldName;?>)  {
    $this->_setDateTimeVal('<?php echo $fieldName;?>', $<?php echo $fieldName;?>);
    return $this;
}