<?php
/**
 * @var string $fieldName
 * @var string $fieldMethod
 * @var string $returnSelf
 * @var string $publicPath
 * @var bool $isPublic
 * @var bool $isMultiple
 */
?>
public function get<?php echo $fieldMethod;?>() {
    return $this->_getFileVal('<?php echo $fieldName;?>');
}
<?php if ($isMultiple): ?>
public function get<?php echo $fieldMethod;?>InternalPath() :array {
    return $this->_getInternalPath('<?php echo $fieldName;?>');
}
public function get<?php echo $fieldMethod;?>Name(int $index = 0) :string {
    return $this->_getFileName('<?php echo $fieldName;?>', $index);
}
public function get<?php echo $fieldMethod;?>Extension(int $index = 0) :string {
    return $this->_getFileExtension('<?php echo $fieldName;?>', $index);
}
public function get<?php echo $fieldMethod;?>Content(int $index = 0) :string {
    return $this->_getFileContent('<?php echo $fieldName;?>', $index);
}
public function get<?php echo $fieldMethod;?>LastModified(int $index = 0) :int|false {
    return $this->_getFileLastModified('<?php echo $fieldName;?>', $index);
}
public function get<?php echo $fieldMethod;?>Size(int $index = 0) :int|false {
    return $this->_getFileSize('<?php echo $fieldName;?>', $index);
}
public function get<?php echo $fieldMethod;?>PublicPath() :array {
    return $this->_getPublicPath('<?php echo $fieldName;?>');
}
<?php else: ?>
public function get<?php echo $fieldMethod;?>InternalPath() :string {
    return $this->_getInternalPath('<?php echo $fieldName;?>');
}
public function get<?php echo $fieldMethod;?>Name() :string {
    return $this->_getFileName('<?php echo $fieldName;?>');
}
public function get<?php echo $fieldMethod;?>Extension() :string {
    return $this->_getFileExtension('<?php echo $fieldName;?>');
}
public function get<?php echo $fieldMethod;?>Content() :string {
    return $this->_getFileContent('<?php echo $fieldName;?>');
}
public function get<?php echo $fieldMethod;?>LastModified() :int|false {
    return $this->_getFileLastModified('<?php echo $fieldName;?>');
}
public function get<?php echo $fieldMethod;?>Size() :int|false {
    return $this->_getFileSize('<?php echo $fieldName;?>');
}
public function get<?php echo $fieldMethod;?>PublicPath() :string {
    return $this->_getPublicPath('<?php echo $fieldName;?>');
}
<?php endif; ?>
public function has<?php echo $fieldMethod;?>() :bool {
    return $this->_hasFileVal('<?php echo $fieldName;?>');
}
public function set<?php echo $fieldMethod;?>WithHttpFile(array $value = null) :static {
    return $this->_setFileValWithHttpFile('<?php echo $fieldName;?>', $value);
}
/** @return <?php echo $returnSelf;?>
 */
public function set<?php echo $fieldMethod;?>(string $<?php echo $fieldName;?>)  {
    $this->_setFileVal('<?php echo $fieldName;?>', $<?php echo $fieldName;?>);
    return $this;
}
/** @return <?php echo $returnSelf;?>
 */
public function set<?php echo $fieldMethod;?>InternalPath(string $<?php echo $fieldName;?>)  {
    $this->_setInternalPath('<?php echo $fieldName;?>', $<?php echo $fieldName;?>);
    return $this;
}
public function get<?php echo $fieldMethod;?>FieldConfig(): ?\Lkt\Factory\Schemas\Fields\FileField {
    return $this->_getFileFieldConfig('<?php echo $fieldName;?>');
}