<?php
/**
 * @var string $fieldName
 * @var string $fieldMethod
 * @var string $returnSelf
 * @var string $component
 * @var string $relatedReturnClass
 * @var string $relatedClassName
 * @var string $relatedQueryCaller
 * @var string $singleReturnType
 * @var string $additionalInput
 * @var string $additionalInputDetection
 * @var bool $isSingleMode
 */
?>
<?php if($isSingleMode): ?>
    <?php if ($additionalInput): ?>
        /** <?php echo $relatedReturnClass; ?> */
        public function get<?php echo $fieldMethod;?>(<?php echo $additionalInput;?>)<?php echo $singleReturnType; ?> {
            $additionalData = [
                <?php echo $additionalInputDetection;?>
            ];
            return $this->_getRelatedValSingle('<?php echo $component; ?>', '<?php echo $fieldName;?>', false, $additionalData);
        }
    <?php else: ?>
        /** <?php echo $relatedReturnClass; ?> */
        public function get<?php echo $fieldMethod;?>()<?php echo $singleReturnType; ?> {
            return $this->_getRelatedValSingle('<?php echo $component; ?>', '<?php echo $fieldName;?>');
        }
    <?php endif ?>

<?php else: ?>

    <?php if ($additionalInput): ?>

        /** <?php echo $relatedReturnClass; ?> */
        public function get<?php echo $fieldMethod;?>(<?php echo $additionalInput;?>): array {
            $additionalData = [
                <?php echo $additionalInputDetection;?>
            ];
            return $this->_getRelatedVal('<?php echo $component; ?>', '<?php echo $fieldName;?>', false, $additionalData);
        }
        /** <?php echo $relatedReturnClass; ?> */
        public function get<?php echo $fieldMethod;?>Page(int $page, Where $where = null): array {
            return $this->_getRelatedPage('<?php echo $component; ?>', '<?php echo $fieldName;?>', $page, $where);
        }
        public function get<?php echo $fieldMethod;?>Count(string $countableField = '', Where $where = null): int {
            return $this->_getRelatedCount('<?php echo $component; ?>', '<?php echo $fieldName;?>', $countableField, $where);
        }
        public function get<?php echo $fieldMethod;?>AmountOfPages(string $countableField = '', Where $where = null): int {
            return $this->_getRelatedAmountOfPages('<?php echo $component; ?>', '<?php echo $fieldName;?>', $countableField, $where);
        }
    <?php else: ?>

        /** <?php echo $relatedReturnClass; ?> */
        public function get<?php echo $fieldMethod;?>(): array {
            return $this->_getRelatedVal('<?php echo $component; ?>', '<?php echo $fieldName;?>');
        }
        /** <?php echo $relatedReturnClass; ?> */
        public function get<?php echo $fieldMethod;?>Page(int $page, Where $where = null): array {
            return $this->_getRelatedPage('<?php echo $component; ?>', '<?php echo $fieldName;?>', $page, $where);
        }
        public function get<?php echo $fieldMethod;?>Count(string $countableField = '', Where $where = null): int {
            return $this->_getRelatedCount('<?php echo $component; ?>', '<?php echo $fieldName;?>', $countableField, $where);
        }
        public function get<?php echo $fieldMethod;?>AmountOfPages(string $countableField = '', Where $where = null): int {
            return $this->_getRelatedAmountOfPages('<?php echo $component; ?>', '<?php echo $fieldName;?>', $countableField, $where);
        }
    <?php endif ?>
<?php endif ?>
public function has<?php echo $fieldMethod;?>() :bool {
    return $this->_hasRelatedVal('<?php echo $component; ?>', '<?php echo $fieldName;?>');
}
/** @return <?php echo $returnSelf;?> */
public function set<?php echo $fieldMethod;?>WithData(array $<?php echo $fieldName;?>)  {
    $this->_setRelatedValWithData('<?php echo $component; ?>', '<?php echo $fieldName;?>', $<?php echo $fieldName;?>);
    return $this;
}
/** @return <?php echo $relatedQueryCaller; ?> */
public function get<?php echo $fieldMethod;?>QueryCaller(): <?php echo $relatedQueryCaller; ?> {
    return $this->_getRelatedCustomQueryCaller('<?php echo $component; ?>', '<?php echo $fieldName;?>');
}