<?php
/**
 * @var string $fieldName
 * @var string $fieldMethod
 * @var string $returnSelf
 * @var string[] $options
 * @var string[] $optionsMethods
 * @var array $comparatorsIn
 * @var bool $enabledEmptyPreset
 */
?>
public function get<?php echo $fieldMethod;?>() :string {
    return $this->_getStringChoiceVal('<?php echo $fieldName;?>');
}
public function has<?php echo $fieldMethod;?>() :bool {
    return $this->_hasStringChoiceVal('<?php echo $fieldName;?>');
}
public function has<?php echo $fieldMethod;?>In(array $values) :bool {
    return $this->_stringChoiceIn('<?php echo $fieldName;?>', $values);
}
public function <?php echo lcfirst($fieldMethod);?>Is(string $value) :bool {
    return $this->_stringChoiceEqual('<?php echo $fieldName;?>', $value);
}
/** @return <?php echo $returnSelf;?>
 */
public function set<?php echo $fieldMethod;?>(string $<?php echo $fieldName;?>)  {
    $this->_setStringChoiceVal('<?php echo $fieldName;?>', $<?php echo $fieldName;?>);
    return $this;
}
<?php foreach ($optionsMethods as $i => $option): ?>
public function <?php echo lcfirst($fieldMethod);?>Is<?php echo $option; ?>() :bool {
    return $this->_getStringChoiceVal('<?php echo $fieldName;?>') === '<?php echo $options[$i]; ?>';
}
/** @return <?php echo $returnSelf;?>
*/
public function set<?php echo $fieldMethod;?><?php echo $option; ?>()  {
    $this->_setStringChoiceVal('<?php echo $fieldName;?>', '<?php echo $options[$i];?>');
    return $this;
}
<?php if ($enabledEmptyPreset): ?>
public static function emptyWith<?php echo $fieldMethod;?>EqualTo<?php echo $option; ?>(): static  {
    return static::getInstance()->set<?php echo $fieldMethod;?><?php echo $option; ?>();
}
<?php endif; ?>
<?php endforeach; ?>

<?php foreach ($comparatorsIn as $comparatorName => $options): ?>
<?php
    $c = count($options);
    if ($c === 0) {
        continue;
    }

    $singleMode = false;
    if ($c === 1) {
        $singleMode = true;
        $optionsText = "'" .implode("','", $options) . "'";

    } else {
        $optionsText = "['" .implode("','", $options) . "']";
    }

?>
public function <?php echo lcfirst($fieldMethod);?>Is<?php echo ucfirst($comparatorName);?>() :bool {
    <?php if ($singleMode): ?>
    return $this->_stringChoiceEqual('<?php echo $fieldName;?>', <?php echo $optionsText; ?>);
    <?php else: ?>
    return $this->_stringChoiceIn('<?php echo $fieldName;?>', <?php echo $optionsText; ?>);
    <?php endif; ?>
}
<?php endforeach; ?>