<?php
/**
 * @var string $fieldName
 * @var string $fieldMethod
 * @var string $returnSelf
 */
?>
public function get<?php echo $fieldMethod;?>() :string {
    return $this->_getStringChoiceVal('<?php echo $fieldName;?>');
}
public function has<?php echo $fieldMethod;?>() :bool {
    return $this->_hasStringChoiceVal('<?php echo $fieldName;?>');
}
/** @return <?php echo $returnSelf;?>
 */
public function set<?php echo $fieldMethod;?>(string $<?php echo $fieldName;?>)  {
    $this->_setStringChoiceVal('<?php echo $fieldName;?>', $<?php echo $fieldName;?>);
    return $this;
}
