<?php
/**
 * @var string $className
 * @var string $component
 * @var string $namespace
 * @var string $extends
 * @var string $implements
 * @var string $traits
 * @var string $methods
 * @var string $returnSelf
 * @var string $queryCaller
 */
?>

namespace <?php echo $namespace?>;

use Lkt\QueryBuilding\Where;
use Lkt\QueryCaller\QueryCaller;
use Lkt\Factory\Instantiator\Instantiator;

class <?php echo $className; ?> extends <?php echo $extends?> <?php echo $implements?> {
    <?php echo $traits?>

    const GENERATED_TYPE = '<?php echo $component; ?>';

    public function __construct($id = 0) {
        parent::__construct($id, static::GENERATED_TYPE);
    }
    <?php echo $methods?>
    /**
    * @return <?php echo $returnSelf;?>[]
    */
    public static function getMany(QueryCaller $queryCaller = null): array
    {
        /** @var <?php echo $returnSelf;?>[] */
        $r = parent::getMany($queryCaller);
        return $r;
    }

    /**
    * @return <?php echo $returnSelf;?>|null
    */
    public static function getOne(QueryCaller $queryCaller = null)
    {
        /** @var <?php echo $returnSelf;?> */
        $r = parent::getOne($queryCaller);
        return $r;
    }

    /** @return <?php echo $queryCaller;?> */
    public static function getQueryCaller()
    {
        /**
        * @var <?php echo $queryCaller;?> $caller
        */
        list($caller) = Instantiator::getCustomQueryCaller(static::GENERATED_TYPE);
        return $caller;
    }

    /** @return <?php echo $queryCaller;?> */
    public static function getFilteredQueryCaller(array $data, array $processRules = null, array $filterRules = null)
    {
        /**
        * @var <?php echo $queryCaller;?> $caller
        */
        list($caller) = Instantiator::getCustomQueryCaller(static::GENERATED_TYPE, $data, $processRules, $filterRules);
        return $caller;
    }

    /**
    * @return <?php echo $returnSelf;?>[]
    */
    public static function getPage(int $page, QueryCaller $queryCaller = null): array
    {
        /** @var <?php echo $returnSelf;?>[] */
        $r = parent::getPage($page, $queryCaller);
        return $r;
    }
}