<?php
/**
 * @var string $className
 * @var string $component
 * @var string $namespace
 * @var string $extends
 * @var string $implements
 * @var string $traits
 * @var string $methods
 * @var string $returnSelf
 * @var string $queryCaller
 */
?>

namespace <?php echo $namespace?>;

use Lkt\QueryBuilding\SelectBuilder;

class <?php echo $className; ?> extends SelectBuilder {

const COMPONENT = '<?php echo $component; ?>';

<?php echo $methods?>
}