<?php
/**
 * @var string $className
 * @var string $component
 * @var string $namespace
 * @var string $extends
 * @var string $implements
 * @var string $traits
 * @var string $methods
 * @var string $returnSelf
 * @var string $queryCaller
 */
?>

namespace <?php echo $namespace?>;

use Lkt\QueryBuilding\Where;
use Lkt\QueryBuilding\DateIntervals\AbstractInterval;

class <?php echo $className; ?> extends Where {

const COMPONENT = '<?php echo $component; ?>';

/** @return <?php echo $queryCaller;?> */
public static function getEmpty()
{
    /** @var <?php echo $queryCaller;?> $r */
    $r = parent::getEmpty();
    return $r;
}

<?php echo $methods?>
}