<?php
/**
 * @var string $column
 * @var string $separator
 * @var string[] $columns
 * @var string $fieldMethod
 * @var string $returnSelf
 * @var bool $canBeNull
 * @var string[] $options
 * @var string[] $optionsMethods
 * @var array $comparatorsIn
 */
?>
<?php foreach (['and', 'or'] as $constraint): ?>
    public function <?php echo $constraint?><?php echo $fieldMethod;?>Equal(string $value) {
        return $this-><?php echo $constraint?>ConcatEqual(<?php echo $columns;?>, "'<?php echo $separator; ?>'", $value);
    }
    public function <?php echo $constraint?><?php echo $fieldMethod;?>Not(string $value) {
        return $this-><?php echo $constraint?>ConcatNot(<?php echo $columns;?>, "'<?php echo $separator; ?>'", $value);
    }
    public function <?php echo $constraint?><?php echo $fieldMethod;?>Like(string $value) {
        return $this-><?php echo $constraint?>ConcatLike(<?php echo $columns;?>, "'<?php echo $separator; ?>'", $value);
    }
    public function <?php echo $constraint?><?php echo $fieldMethod;?>NotLike(string $value) {
        return $this-><?php echo $constraint?>ConcatNotLike(<?php echo $columns;?>, "'<?php echo $separator; ?>'", $value);
    }
    public function <?php echo $constraint?><?php echo $fieldMethod;?>BeginsLike(string $value) {
        return $this-><?php echo $constraint?>ConcatBeginsLike(<?php echo $columns;?>, "'<?php echo $separator; ?>'", $value);
    }
    public function <?php echo $constraint?><?php echo $fieldMethod;?>NotBeginsLike(string $value) {
        return $this-><?php echo $constraint?>ConcatNotBeginsLike(<?php echo $columns;?>, "'<?php echo $separator; ?>'", $value);
    }
    public function <?php echo $constraint?><?php echo $fieldMethod;?>EndsLike(string $value) {
        return $this-><?php echo $constraint?>ConcatEndsLike(<?php echo $columns;?>, "'<?php echo $separator; ?>'", $value);
    }
    public function <?php echo $constraint?><?php echo $fieldMethod;?>NotEndsLike(string $value) {
        return $this-><?php echo $constraint?>ConcatNotEndsLike(<?php echo $columns;?>, "'<?php echo $separator; ?>'", $value);
    }
<?php endforeach; ?>