<?php
/**
 * @var string $column
 * @var string $fieldMethod
 * @var string $returnSelf
 * @var bool $canBeNull
 */
?>
/** @return <?php echo $returnSelf;?> */
public static function <?php echo $fieldMethod;?>Equal(string $value) {
    return static::stringEqual('<?php echo $column;?>', $value);
}
/** @return <?php echo $returnSelf;?> */
public static function <?php echo $fieldMethod;?>Not(string $value) {
    return static::stringNot('<?php echo $column;?>', $value);
}
/** @return <?php echo $returnSelf;?> */
public static function <?php echo $fieldMethod;?>Like(string $value) {
    return static::stringLike('<?php echo $column;?>', $value);
}
/** @return <?php echo $returnSelf;?> */
public static function <?php echo $fieldMethod;?>NotLike(string $value) {
    return static::stringNotLike('<?php echo $column;?>', $value);
}
/** @return <?php echo $returnSelf;?> */
public static function <?php echo $fieldMethod;?>BeginsLike(string $value) {
    return static::stringBeginsLike('<?php echo $column;?>', $value);
}
/** @return <?php echo $returnSelf;?> */
public static function <?php echo $fieldMethod;?>NotBeginsLike(string $value) {
    return static::stringNotBeginsLike('<?php echo $column;?>', $value);
}
/** @return <?php echo $returnSelf;?> */
public static function <?php echo $fieldMethod;?>EndsLike(string $value) {
    return static::stringEndsLike('<?php echo $column;?>', $value);
}
/** @return <?php echo $returnSelf;?> */
public static function <?php echo $fieldMethod;?>NotEndsLike(string $value) {
    return static::stringNotEndsLike('<?php echo $column;?>', $value);
}
/** @return <?php echo $returnSelf;?> */
public static function <?php echo $fieldMethod;?>In(array $values) {
    return static::stringIn('<?php echo $column;?>', $values);
}
/** @return <?php echo $returnSelf;?> */
public static function <?php echo $fieldMethod;?>NotIn(array $values) {
    return static::stringNotIn('<?php echo $column;?>', $values);
}
<?php if($canBeNull): ?>
/** @return <?php echo $returnSelf;?> */
public static function <?php echo $fieldMethod;?>IsNull() {
    return static::isNull('<?php echo $column;?>');
}
/** @return <?php echo $returnSelf;?> */
public static function <?php echo $fieldMethod;?>IsNotNull() {
    return static::isNotNull('<?php echo $column;?>');
}
<?php endif; ?>